send_command:
  name: Send Command
  description: Sends a command to the server to run.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    command:
      name: Command
      description: Command to send to the server.
      required: true
      example: "echo"
      selector:
        text:
    arguments:
      name: Arguments
      description: Arguments to send to the server.
      required: false
      default: ""
      example: "hello"
      selector:
        text:
open:
  name: Open Path/URL
  description: Open a URL or file on the server using the default application.
  fields:
    bridge:
      name: Bridge
      description: The server to talk to.
      required: true
      selector:
        device:
          integration: system_bridge
    path:
      name: Path/URL
      description: Path/URL to open.
      required: true
      example: "https://www.home-assistant.io"
      selector:
        text:
send_keypress:
  name: Send Keyboard Keypress
  description: Sends a keyboard keypress.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    key:
      name: Key
      description: "Key to press. List available here: http://robotjs.io/docs/syntax#keys"
      required: true
      example: "audio_play"
      selector:
        text:
    modifiers:
      name: Modifiers
      description: "List of modifier(s). Accepts alt, command/win, control, and shift."
      required: false
      default: ""
      example:
        - "control"
        - "shift"
      selector:
        text:
send_text:
  name: Send Keyboard Text
  description: Sends text for the server to type.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    text:
      name: Text
      description: "Text to type."
      required: true
      example: "Hello world"
      selector:
        text:
