set_light_sleep_timer:
  name: Set light sleep timer
  description: Set a sleep timer on a Modern Forms light.
  target:
    entity:
      integration: modern_forms
      domain: light
  fields:
    sleep_time:
      name: Sleep Time
      description: Number of minutes to set the timer.
      required: true
      example: "900"
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
clear_light_sleep_timer:
  name: Clear light sleep timer
  description: Clear the sleep timer on a Modern Forms light.
  target:
    entity:
      integration: modern_forms
      domain: light
set_fan_sleep_timer:
  name: Set fan sleep timer
  description: Set a sleep timer on a Modern Forms fan.
  target:
    entity:
      integration: modern_forms
      domain: fan
  fields:
    sleep_time:
      name: Sleep Time
      description: Number of minutes to set the timer.
      required: true
      example: "900"
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
clear_fan_sleep_timer:
  name: Clear fan sleep timer
  description: Clear the sleep timer on a Modern Forms fan.
  target:
    entity:
      integration: modern_forms
      domain: fan
