send_ir_code:
  name: Send IR code
  description: Set an IR code as a state attribute for a MySensors IR device switch and turn the switch on.
  fields:
    entity_id:
      name: Entity
      description: Name of entity that should have the IR code set and be turned on. Platform dependent.
      selector:
        entity:
          integration: mysensors
          domain: switch
    V_IR_SEND:
      name: IR send
      description: IR code to send.
      required: true
      example: "0xC284"
      selector:
        text:
