custom_cleaning:
  name: Zone Cleaning service
  description: Zone Cleaning service call specific to Neato Botvacs.
  target:
    entity:
      integration: neato
      domain: vacuum
  fields:
    mode:
      name: Set cleaning mode
      description: "Set the cleaning mode: 1 for eco and 2 for turbo. Defaults to turbo if not set."
      default: 2
      selector:
        number:
          min: 1
          max: 2
          mode: box
    navigation:
      name: Set navigation mode
      description: "Set the navigation mode: 1 for normal, 2 for extra care, 3 for deep. Defaults to normal if not set."
      default: 1
      selector:
        number:
          min: 1
          max: 3
          mode: box
    category:
      name: Use cleaning map
      description: "Whether to use a persistent map or not for cleaning (i.e. No go lines): 2 for no map, 4 for map. Default to using map if not set (and fallback to no map if no map is found)."
      default: 4
      selector:
        number:
          min: 2
          max: 4
          step: 2
          mode: box
    zone:
      name: Name of the zone to clean (Only Botvac D7)
      description: Only supported on the Botvac D7. Name of the zone to clean. Defaults to no zone i.e. complete house cleanup.
      example: "Kitchen"
      selector:
        text:
