# Describes the format for available Z-Wave services

change_association:
  name: Change association
  description: Change an association in the Z-Wave network.
  fields:
    association:
      name: Association
      description: Specify add or remove association
      required: true
      example: add
      selector:
        text:
    node_id:
      name: Node ID
      description: Node id of the node to set association for.
      required: true
      selector:
        number:
          min: 1
          max: 255
    target_node_id:
      name: Target node ID
      description: Node id of the node to associate to.
      required: true
      selector:
        number:
          min: 1
          max: 255
    group:
      name: Group
      description: Group number to set association for.
      required: true
      selector:
        number:
          min: 1
          max: 5
    instance:
      name: Instance
      description: Instance of multichannel association.
      default: 0
      selector:
        number:
          min: 0
          max: 255

add_node:
  name: Add node
  description: Add a new (unsecure) node to the Z-Wave network. Refer to OZW_Log.txt for progress.

add_node_secure:
  name: Add node secure
  description: Add a new node to the Z-Wave network with secure communications. Secure network key must be set, this process will fallback to add_node (unsecure) for unsupported devices. Note that unsecure devices can't directly talk to secure devices. Refer to OZW_Log.txt for progress.

cancel_command:
  name: Cancel command
  description: Cancel a running Z-Wave controller command. Use this to exit add_node, if you weren't going to use it but activated it.

heal_network:
  name: Heal network
  description: Start a Z-Wave network heal. This might take a while and will slow down the Z-Wave network greatly while it is being processed. Refer to OZW_Log.txt for progress.
  fields:
    return_routes:
      name: Return routes
      description: Whether or not to update the return routes from the nodes to the controller.
      default: false
      selector:
        boolean:

heal_node:
  name: Heal node
  description: Start a Z-Wave node heal. Refer to OZW_Log.txt for progress.
  fields:
    return_routes:
      name: Return routes
      description: Whether or not to update the return routes from the node to the controller.
      default: false
      selector:
        boolean:

remove_node:
  name: Remove node
  description: Remove a node from the Z-Wave network. Refer to OZW_Log.txt for progress.

remove_failed_node:
  name: Remove failed node
  description: This command will remove a failed node from the network. The node should be on the controller's failed nodes list, otherwise this command will fail. Refer to OZW_Log.txt for progress.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to remove.
      required: true
      selector:
        number:
          min: 1
          max: 255

replace_failed_node:
  name: Replace failed node
  description: Replace a failed node with another. If the node is not in the controller's failed nodes list, or the node responds, this command will fail. Refer to OZW_Log.txt for progress.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to replace.
      required: true
      selector:
        number:
          min: 1
          max: 255

set_config_parameter:
  name: Set config parameter
  description: Set a config parameter to a node on the Z-Wave network.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to set config parameter to.
      required: true
      selector:
        number:
          min: 1
          max: 255
    parameter:
      name: Parameter
      description: Parameter number to set.
      required: true
      selector:
        number:
          min: 1
          max: 255
    value:
      name: Value
      description: Value to set for parameter. (String value for list and bool parameters, integer for others).
      required: true
      selector:
        text:
    size:
      name: Size
      description: Set the size of the parameter value. Only needed if no parameters are available.
      default: 2
      selector:
        number:
          min: 1
          max: 255

set_node_value:
  name: Set node value
  description: Set the value for a given value_id on a Z-Wave device.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to set the value on.
      required: true
      selector:
        number:
          min: 1
          max: 255
    value_id:
      name: Value ID
      description: Value id of the value to set (integer or string).
      required: true
      selector:
        text:
    value:
      name: Value
      description: Value to set (integer or string).
      required: true
      selector:
        text:

refresh_node_value:
  name: Refresh node value
  description: Refresh the value for a given value_id on a Z-Wave device.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to refresh value from.
      required: true
      selector:
        number:
          min: 1
          max: 255
    value_id:
      name: Value ID
      description: Value id of the value to refresh.
      required: true
      selector:
        text:

set_poll_intensity:
  name: Set poll intensity
  description: Set the polling interval to a nodes value
  fields:
    node_id:
      name: Node ID
      description: ID of the node to set polling to.
      required: true
      selector:
        number:
          min: 1
          max: 255
    value_id:
      name: Value ID
      description: ID of the value to set polling to.
      example: 72037594255792737
      required: true
      selector:
        text:
    poll_intensity:
      name: Poll intensity
      description: The intensity to poll, 0 = disabled, 1 = Every time through list, 2 = Every second time through list...
      required: true
      selector:
        number:
          min: 0
          max: 100

print_config_parameter:
  name: Print configuration parameter
  description: Prints a Z-Wave node config parameter value to log.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to print the parameter from.
      required: true
      selector:
        number:
          min: 1
          max: 255
    parameter:
      name: Parameter
      description: Parameter number to print.
      required: true
      selector:
        number:
          min: 1
          max: 255

print_node:
  name: Print node
  description: Print all information about z-wave node.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to print.
      required: true
      selector:
        number:
          min: 1
          max: 255

refresh_entity:
  name: Refresh entity
  description: Refresh zwave entity.
  fields:
    entity_id:
      name: Entity
      description: Name of the entity to refresh.
      required: true
      selector:
        entity:
          integration: zwave

refresh_node:
  name: Refresh node
  description: Refresh zwave node.
  fields:
    node_id:
      name: Node ID
      description: ID of the node to refresh.
      required: true
      selector:
        number:
          min: 1
          max: 255

set_wakeup:
  name: Set wakeup
  description: Sets wake-up interval of a node.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to set the wake-up interval for.
      required: true
      selector:
        number:
          min: 1
          max: 255
    value:
      name: Value
      description: Value of the interval to set.
      required: true
      selector:
        text:

start_network:
  name: Start network
  description: Start the Z-Wave network. This might take a while, depending on how big your Z-Wave network is.

stop_network:
  name: Stop network
  description: Stop the Z-Wave network, all updates into Home Assistant will stop.

soft_reset:
  name: Soft reset
  description: This will reset the controller without removing its data. Use carefully because not all controllers support this. Refer to your controller's manual.

test_network:
  name: Test network
  description: This will send test to nodes in the Z-Wave network. This will greatly slow down the Z-Wave network while it is being processed. Refer to OZW_Log.txt for progress.

test_node:
  name: Test node
  description: This will send test messages to a node in the Z-Wave network. This could bring back dead nodes.
  fields:
    node_id:
      name: Node ID
      description: ID of the node to send test messages to.
      required: true
      selector:
        number:
          min: 1
          max: 255
    messages:
      name: Messages
      description: Amount of test messages to send.
      default: 1
      selector:
        number:
          min: 1
          max: 100

rename_node:
  name: Rename node
  description: Set the name of a node. This will also affect the IDs of all entities in the node.
  fields:
    node_id:
      name: Node ID
      description: ID of the node to rename.
      required: true
      selector:
        number:
          min: 1
          max: 255
    update_ids:
      name: Update IDs
      description: Rename the entity IDs for entities of this node.
      default: false
      selector:
        boolean:
    name:
      name: Name
      description: New Name
      required: true
      example: "kitchen"
      selector:
        text:

rename_value:
  name: Rename value
  description: Set the name of a node value. This will affect the ID of the value entity. Value IDs can be queried from /api/zwave/values/{node_id}
  fields:
    node_id:
      name: Node ID
      description: ID of the node to rename.
      required: true
      selector:
        number:
          min: 1
          max: 255
    value_id:
      name: Value ID
      description: ID of the value to rename.
      example: 72037594255792737
      required: true
      selector:
        text:
    update_ids:
      name: Update IDs
      description: Update the entity ID for this value's entity.
      default: false
      selector:
        boolean:
    name:
      name: Name
      description: New Name
      example: "Luminosity"
      required: true
      selector:
        text:

reset_node_meters:
  name: Reset node meters
  description: Resets the meter counters of a node.
  fields:
    node_id:
      name: Node ID
      description: Node id of the device to reset meters for.
      required: true
      selector:
        number:
          min: 1
          max: 255
    instance:
      name: Instance
      description: Instance of association.
      default: 1
      selector:
        number:
          min: 1
          max: 100
