# Describes the format for available Risco services

bypass_zone:
  name: Bypass zone
  description: Bypass a Risco Zone
  target:
    entity:
      integration: risco
      domain: binary_sensor

unbypass_zone:
  name: Unbypass zone
  description: Unbypass a Risco Zone
  target:
    entity:
      integration: risco
      domain: binary_sensor
