# Describes the format for available hue services

hue_activate_scene:
  name: Activate scene
  description: Activate a hue scene stored in the hue hub.
  fields:
    group_name:
      name: Group
      description: Name of hue group/room from the hue app.
      example: "Living Room"
      selector:
        text:
    scene_name:
      name: Scene
      description: Name of hue scene from the hue app.
      example: "Energize"
      selector:
        text:
    dynamic:
      name: Dynamic
      description: Enable dynamic mode of the scene (V2 bridges and supported scenes only).
      selector:
        boolean:
