start_record:
  name: Start record
  description: Start QVR Pro recording on specified channel.
  fields:
    guid:
      name: GUID
      description: GUID of the channel to start recording.
      required: true
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:

stop_record:
  name: Stop record
  description: Stop QVR Pro recording on specified channel.
  fields:
    guid:
      name: GUID
      description: GUID of the channel to stop recording.
      required: true
      example: "245EBE933C0A597EBE865C0A245E0002"
      selector:
        text:
