set_vane_horizontal:
  name: Set vane horizontal
  description: Sets horizontal vane position.
  target:
    entity:
      integration: melcloud
      domain: climate
  fields:
    position:
      name: Position
      description: >
        Horizontal vane position. Possible options can be found in the
        vane_horizontal_positions state attribute.
      required: true
      example: "auto"
      selector:
        text:

set_vane_vertical:
  name: Set vane vertical
  description: Sets vertical vane position.
  target:
    entity:
      integration: melcloud
      domain: climate
  fields:
    position:
      name: Position
      description: >
        Vertical vane position. Possible options can be found in the
        vane_vertical_positions state attribute.
      required: true
      example: "auto"
      selector:
        text:
