update:
  name: Update
  description: Updates the list of conversations.

send_message:
  name: Send message
  description: Send a notification to a specific target.
  fields:
    target:
      name: Target
      description: List of targets with id or name.
      required: true
      example: '[{"id": "UgxrXzVrARmjx_C6AZx4AaABAagBo-6UCw"}, {"name": "Test Conversation"}]'
      selector:
        object:
    message:
      name: Message
      description: List of message segments, only the "text" field is required in every segment.
      required: true
      example: '[{"text":"test", "is_bold": false, "is_italic": false, "is_strikethrough": false, "is_underline": false, "parse_str": false, "link_target": "http://google.com"}]'
      selector:
        object:
    data:
      name: Data
      description: Other options ['image_file' / 'image_url']
      example: '{ "image_file": "file" }'
      selector:
        object:

reconnect:
  name: Reconnect
  description: Reconnect the bot.
