# Describes the format for available Envisalink services.

alarm_keypress:
  name: Alarm keypress
  description: Send custom keypresses to the alarm.
  fields:
    entity_id:
      name: Entity
      description: Name of the alarm control panel to trigger.
      required: true
      selector:
        entity:
          integration: envisalink
          domain: alarm_control_panel
    keypress:
      name: Keypress
      description: "String to send to the alarm panel (1-6 characters)."
      required: true
      example: "*71"
      selector:
        text:

invoke_custom_function:
  name: Invoke custom function
  description: >
    Allows users with DSC panels to trigger a PGM output (1-4).
    Note that you need to specify the alarm panel's "code" parameter for this to work.
  fields:
    partition:
      name: Partition
      description: >
        The alarm panel partition to trigger the PGM output on.
        Typically this is just "1".
      required: true
      example: "1"
      selector:
        text:
    pgm:
      name: PGM
      description: The PGM number to trigger on the alarm panel.
      required: true
      selector:
        number:
          min: 1
          max: 4
