write:
  name: Write
  description: Call ebusd write command.
  fields:
    call:
      name: Call
      description: Property name and value to set
      required: true
      example: '{"name": "Hc1MaxFlowTempDesired", "value": 21}'
      selector:
        object:
