select_option:
  name: Select
  description: Select an option of an select entity.
  target:
    entity:
      domain: select
  fields:
    option:
      name: Option
      description: Option to be selected.
      required: true
      example: '"Item A"'
      selector:
        text:
