turn_on:
  name: Turn on
  description:
    Set the light RGB to the predominant color found in the image provided by
    URL or file path.
  target:
    entity:
      domain: light
  fields:
    color_extract_url:
      name: URL
      description:
        The URL of the image we want to extract RGB values from. Must be allowed
        in allowlist_external_urls.
      example: https://www.example.com/images/logo.png
      selector:
        text:
    color_extract_path:
      name: Path
      description:
        The full system path to the image we want to extract RGB values from.
        Must be allowed in allowlist_external_dirs.
      example: /opt/images/logo.png
      selector:
        text:
