start_engine:
  name: Start engine
  description: Start the vehicle engine.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to start
      required: true
      selector:
        device:
          integration: mazda
stop_engine:
  name: Stop engine
  description: Stop the vehicle engine.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to stop
      required: true
      selector:
        device:
          integration: mazda
turn_on_hazard_lights:
  name: Turn on hazard lights
  description: Turn on the vehicle hazard lights. The lights will flash briefly and then turn off.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to turn hazard lights on
      required: true
      selector:
        device:
          integration: mazda
turn_off_hazard_lights:
  name: Turn off hazard lights
  description: Turn off the vehicle hazard lights if they have been manually turned on from inside the vehicle.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to turn hazard lights off
      required: true
      selector:
        device:
          integration: mazda
send_poi:
  name: Send POI
  description: Send a GPS location to the vehicle's navigation system as a POI (Point of Interest). Requires a navigation SD card installed in the vehicle.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to send the GPS location to
      required: true
      selector:
        device:
          integration: mazda
    latitude:
      name: Latitude
      description: The latitude of the location to send
      example: 12.34567
      required: true
      selector:
        number:
          min: -90
          max: 90
          unit_of_measurement: °
          mode: box
    longitude:
      name: Longitude
      description: The longitude of the location to send
      example: -34.56789
      required: true
      selector:
        number:
          min: -180
          max: 180
          unit_of_measurement: °
          mode: box
    poi_name:
      name: POI name
      description: A friendly name for the location
      example: Work
      required: true
      selector:
        text:
start_charging:
  name: Start charging
  description: Start charging the vehicle. For electric vehicles only.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to start charging
      required: true
      selector:
        device:
          integration: mazda
stop_charging:
  name: Stop charging
  description: Stop charging the vehicle. For electric vehicles only.
  fields:
    device_id:
      name: Vehicle
      description: The vehicle to stop charging
      required: true
      selector:
        device:
          integration: mazda
