set_custom_effect:
  description: Set a custom light effect.
  target:
    entity:
      integration: flux_led
      domain: light
  fields:
    colors:
      description: List of colors for the custom effect (RGB). (Max 16 Colors)
      example: |
        - [255,0,0]
        - [0,255,0]
        - [0,0,255]
      required: true
      selector:
        object:
    speed_pct:
      description: Effect speed for the custom effect (0-100).
      example: 80
      default: 50
      required: false
      selector:
        number:
          min: 1
          step: 1
          max: 100
          unit_of_measurement: "%"
    transition:
      description: Effect transition.
      example: 'jump'
      default: 'gradual'
      required: false
      selector:
        select:
          options:
            - "gradual"
            - "jump"
            - "strobe"
